#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# 在 xv6 的构建过程中，这个脚本扮演着代码生成器的角色。

# 为什么需要这个脚本？
# 我们先回顾一下系统调用的过程：

# 一个用户程序（用C语言编写）想要执行一个系统调用，比如调用 fork()。
# 这个 fork() 函数调用不能直接跳转到内核的代码，因为用户程序和内核在不同的特权级，内存空间也是隔离的。
# 它需要通过一个特殊的、预先定义好的**“陷阱 (trap)”机制**来请求内核的服务。
# 在RISC-V架构中，这个机制的具体实现是：
# a. 把系统调用号（一个唯一的整数，用来告诉内核“我想要哪个服务”）放入指定的寄存器（在xv6中是 a7）。
# b. 执行一条特殊的指令 ecall (Environment Call)。
# c. ecall 会触发硬件中断，CPU切换到内核态，并跳转到内核预设好的陷阱处理程序。
# d. 内核的陷阱处理程序查看 a7 寄存器的值，就知道用户想要 fork，然后去执行内核中的 sys_fork() 函数。
# 问题来了：每个系统调用（fork, exit, read 等）都需要重复 a, b, c 这几个汇编步骤。我们总不能为每个系统调用都手写一遍几乎一模一样的汇编代码吧？这既繁琐又容易出错。

# usys.pl 这个脚本就是为了自动化这个过程而生的。

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");